[project]
name = "14_eu_fact_force"
version = "0.1.0"
description = "A narrative-centric platform to counter health misinformation by connecting evidence-based responses with public health actors and community leaders across Europe"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
